# Copyright (C) 2019-2020 Cardinal
# Vincent STEHLY--CALISTO, vincentstehly@hotmail.fr

# Paths
# Engine main paths
SET(CARDINAL_ROOT_DIR            ${CMAKE_SOURCE_DIR})
SET(CARDINAL_BIN_DIR             ${CARDINAL_ROOT_DIR}/Bin)
SET(CARDINAL_LIB_DIR             ${CARDINAL_ROOT_DIR}/Lib)
SET(CARDINAL_ENGINE_DIR          ${CARDINAL_ROOT_DIR}/Engine)
SET(CARDINAL_ENGINE_HEADER_DIR   ${CARDINAL_ENGINE_DIR}/Header)
SET(CARDINAL_ENGINE_SOURCE_DIR   ${CARDINAL_ENGINE_DIR}/Source)
SET(CARDINAL_THIRD_PARTY_DIR     ${CARDINAL_ENGINE_DIR}/ThirdParty)
SET(CARDINAL_ENGINE_RESOURCE_DIR ${CARDINAL_ENGINE_DIR}/Resources)

# Engine binaries paths
# Debug
SET(CARDINAL_BIN_DIR32_D  ${CARDINAL_BIN_DIR}/x86_d)
SET(CARDINAL_LIB_DIR32_D  ${CARDINAL_LIB_DIR}/x86_d)
SET(CARDINAL_BIN_DIR64_D  ${CARDINAL_BIN_DIR}/x64_d)
SET(CARDINAL_LIB_DIR64_D  ${CARDINAL_LIB_DIR}/x64_d)

# Release
SET(CARDINAL_BIN_DIR32_R  ${CARDINAL_BIN_DIR}/x86_r)
SET(CARDINAL_LIB_DIR32_R  ${CARDINAL_LIB_DIR}/x86_r)
SET(CARDINAL_BIN_DIR64_R  ${CARDINAL_BIN_DIR}/x64_r)
SET(CARDINAL_LIB_DIR64_R  ${CARDINAL_LIB_DIR}/x64_r)

# Names
# Engine runtime names
SET(CARDINAL_RUNTIME32_D CardinalRuntime32_d)
SET(CARDINAL_RUNTIME64_D CardinalRuntime64_d)
SET(CARDINAL_RUNTIME32_R CardinalRuntime32_r)
SET(CARDINAL_RUNTIME64_R CardinalRuntime64_r)

# Engine runtime libraries names
SET(CARDINAL_RUNTIME_LIBRARY32_D CardinalRuntimeLibrary32_d)
SET(CARDINAL_RUNTIME_LIBRARY64_D CardinalRuntimeLibrary64_d)
SET(CARDINAL_RUNTIME_LIBRARY32_R CardinalRuntimeLibrary32_r)
SET(CARDINAL_RUNTIME_LIBRARY64_R CardinalRuntimeLibrary64_r)

# Engine unit test names
SET(CARDINAL_RUNTIME_UNIT_TEST32_D CardinalRuntimeUnitTest32_d)
SET(CARDINAL_RUNTIME_UNIT_TEST64_D CardinalRuntimeUnitTest64_d)
SET(CARDINAL_RUNTIME_UNIT_TEST32_R CardinalRuntimeUnitTest32_r)
SET(CARDINAL_RUNTIME_UNIT_TEST64_R CardinalRuntimeUnitTest64_r)